- backend/routes/proposals.js
- backend/utils/recaptcha/recaptcha.js
- frontend/src/components/Recaptcha.svelte
- frontend/src/pages/CreateProject.svelte
- frontend/src/pages/SubmitProposal.svelte
- frontend/src/utils/config.js
Add recaptcha protection to:
- Create proposal
- Update proposal
- Create project
- Update project
> Add captcha

- backend/utils/airtable/utils.js
Add `Proposal Title` to Airtable
> Add `Proposal Title` to Airtable

- backend/routes/admin.js
> Add `/admin/create` endpoint

- backend/routes/admin.js
- backend/utils/airtable/utils.js
Update `deliverableChecklist` field when proposal is completed
> Update `deliverableChecklist` when proposal is completed

- backend/routes/project.js
- backend/utils/airtable/utils.js
> If submission deadline has passed, return error

- frontend/src/pages/CreateProject.svelte
- frontend/src/pages/SubmitProposal.svelte
> Display server side error messages

- backend/models/Proposal.js
- backend/routes/project.js
- backend/routes/proposal.js
- backend/utils/airtable/utils.js
- frontend/src/pages/SubmitProposal.svelte
- Add minimum funding requested field to the proposal form
- Add min funding requested to Airtable update-create functions
- Return an error if min funding requested is higher than the funding requested when creating/updating the proposal.
Before merging this PR:
- Add `Minimum USD Requested` field to Airtable
> Add min funding requested

- backend/routes/middlewares/index.js
- backend/routes/project.js
- backend/utils/airtable/utils.js
Return an error if the project has an undelivered proposal when creating a proposal.
> Check if project is in badstate

- backend/scripts/airtable/dumpProposals.js
> Check via `RecordId` in migration script

- backend/routes/middlewares/index.js
- backend/routes/project.js
- backend/routes/proposal.js
- backend/utils/airtable/utils.js
- frontend/src/pages/SubmitProposal.svelte
Fixes #58 .
- Fix current round not found bug: last round = the round with latest 'round starts' , active round = voting not started & round started
- Submit the proposal for the next round if the due diligence period started.
> Fix current round not found

- backend/routes/project.js
> Fix blocking requests

- backend/routes/admin.js
Require level 4 for reviewing earmarks and deliverables
> Require level 4 for reviewing earmarks and deliverables

- backend/models/Project.js
- backend/models/Proposal.js
- backend/models/Signer.js
Trim project name and proposal title
> Trim project name and proposal title

- backend/routes/project.js
- backend/utils/airtable/utils.js
> Fix category id not found

- backend/routes/project.js
- backend/utils/airtable/utils.js
Fix string sum - convert round number to int
> Fix string sum - convert round number to int

- backend/package-lock.json
- backend/package.json
- backend/routes/index.js
- backend/routes/round.js
- backend/utils/redis/index.js
- backend/utils/redis/round.js
- docker-compose.yml
- frontend/src/pages/SubmitProposal.svelte
Closes #60 
+ Redis client & service
+ `/round` endpoint
+ Make it obvious which round the proposal will be submitted.
> Make it obvious which round the proposal will be submitted

- backend/routes/round.js
- backend/utils/redis/round.js
> Cache round object as JSON

- backend/scripts/staging/create-dummy-proposals.js
- backend/utils/recaptcha/recaptcha.js
Dummy proposal and project generator script.
> Dummy proposal and project generator script

- backend/routes/admin.js
- backend/utils/airtable/utils.js
Closes #120 
- Set proposal state to completed when deliverables are accepted
> Set proposal state to completed when deliverables are accepted

- frontend/src/pages/ProposalPage.svelte
- frontend/src/pages/SubmitProposal.svelte
- frontend/src/store.js
- frontend/src/stores/proposal.js
Staging is 60 commits ahead of main. 
Deploying hotfix.
As implemented in [PR 123](https://github.com/oceanprotocol/oceandao-proposal-portal/pull/123)
> Reimplementing changes from fix/115-min-usd-field into main.

- frontend/src/pages/AdminReviewProposalDeliverables.svelte
- frontend/src/pages/AdminReviewProposalEarmark.svelte
> Admin Portal - Provide link to port proposal from FE

- backend/routes/admin.js
Fixes #87
- Remove "Admin" headline from the reply
> Fix admin discourse response everything is bold

- backend/models/Proposal.js
- backend/routes/project.js
Response example:
```json
{
"level": "New Project",
"ceiling": 3000,
"projectCategory": "build",
"grantsProposed": 1,
"grantsReceived": 0,
"grantsCompleted": 0,
"availableEarmaks": [
"newproject",
"coretech",
"general",
"outreach"
]
}
```
> Add `/state/:projectId` endpoint

- backend/routes/project.js
- backend/routes/proposal.js
- backend/utils/redis/cacher.js
Cache proposals on create and update
> Cache proposals on create and update

- frontend/src/pages/SubmitProposal.svelte
> Set loading false if submit proposal fields are not valid

- backend/routes/proposal.js
- backend/utils/discourse/utils.js
- frontend/src/pages/SubmitProposal.svelte
Fixes #146 #22
- Check if the proposal description is null
- New discourse topic order #22
> Proposal description can be null when creating discourse topic

- backend/routes/project.js
- backend/routes/proposal.js
- backend/routes/utils/proposal-utils.js
- backend/utils/airtable/utils.js
Fixes #144
- Enable proposal earmark changes in the backend
- Modularize `getAvailableEarmarks`
> Enable proposal earmark changes in backend

- backend/routes/proposal.js
Fixes #137 .
- [Check 500 Ocean when updating proposal](https://github.com/oceanprotocol/oceandao-proposal-portal/commit/0c8558293d1cec4fc7a07619997bbe33f6c43614)
> Check 500 Ocean when updating proposal

- backend/routes/project.js
Fixes # .
- Can create proposal should only check funded
- 
-
> HOTFIX - Can create proposal should only check funded

- backend/routes/utils/proposal-utils.js
Fixes [#155](https://github.com/oceanprotocol/oceandao-proposal-portal/issues/155)
> Updated earmark selection to make it more flexible.

- backend/routes/proposal.js
> Fix minUSDrequested not updated if 0

- backend/routes/project.js
- backend/utils/airtable/utils.js
Fixes 1/2 of #102
- Enable project category change
> Enable project category change

- backend/routes/admin.js
Fixes #168
- [Check fields /completeProposal](https://github.com/oceanprotocol/oceandao-proposal-portal/commit/3f3957713f345cb046f570d75c6845ead26d9601)
> Fix leaving the description blank causes a crash
